apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: gateway
  name: gateway
spec:
  containers:
  - image: s4saif/gateway:v3
    name: gateway
    ports:
      - containerPort: 9000
        name: gateway
      - containerPort: 3000
        name: app
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
