apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: gateway
  name: my-service
spec:
  ports:
  - name: port-1
    port: 9000
    protocol: TCP
    targetPort: 9000
  - name: port-2
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    run: gateway
  type: LoadBalancer
status:
  loadBalancer: {}
